openapi: 3.0.0
info:
  title: Paysafe Bank Account Validation API
  description: |-
    # Release Notes

    | Version   | Date          | Details |
    |---        |---            |---      |
    | 1.0       | April 2023    | <ul><li>Document Release</li></ul> |

    <a name="apikey" title="Authentication"></a>

    # Authentication

    In order for you to use the Paysafe REST API, Paysafe must first set you up on their system and provide you with an API key. Your API key looks something like this:

    * Key Username – MerchantXYZ

    * Key Password – B-tst1-0-51ed39e4-312d02345d3f123120881dff9bb4020a89e8ac44cdfdcecd702151182fdc952272661d290ab2e5849e31bb03deede7e

    Note this is not the same as your Merchant Back Office username and password.
    The case-sensitive API key is sent using HTTP Basic Authentication. To use HTTP Basic Authentication, you must send the API key credentials using the Authorization header with every request. The Authorization header is constructed as follows:

    1. The Key Username and Key Password are combined into a string separated by a colon, e.g.,“Key Username:Key Password”.

    2. The resulting string literal is then encoded using Base64.

    3. The authorization method and a space (i.e., “Basic”) are then put beforethe encoded string.

    For example, using the Key Username and Password examples above, the header is formed as follows:

    ``Authorization: Basic
    TWVyY2hhbnRYWVo6Qi10c3QxLTAtNTFlZDM5ZTQtMzEyZDAyMzQ1ZDNmMTIzMTIwODgxZGZmOWJiNDAyMGE4OWU4YWM0NGNkZmRjZWNkNzAyMTUxMTgyZmRjOTU yMjcyNjYxZDI5MGFiMmU1ODQ5ZTMxYmIwM2RlZWRlN2U=``

    For additional details, please refer to [http://en.wikipedia.org/wiki/Basic_access_authentication](http://en.wikipedia.org/wiki/Basic_access_authentication).

    **Note:** Your Production API key will be different from your Test API key. Contact your account manager for details. You must keep your API keys safe and ensure that it is used appropriately for your needs.

    # URLs

    ##  Test URL

    In order to test your integration with Paysafe, use the following Test URL:

    `https://api.test.paysafe.com`

    For example:

    `https://api.test.paysafe.com/bankaccountvalidator/v1/verifiedme/accounts/{account_id}/verifications`

    ## Production URL

    In order to process live requests with Paysafe, use the following Production URL:

    `https://api.paysafe.com`

    For example:

    `https://api.paysafe.com/bankaccountvalidator/v1/verifiedme/accounts/{account_id}/verifications`

    # Pagination

    In the case where an API GET request returns multiple results, Paysafe returns the first 10 records by default and uses HATEOAS links to provide page navigation. In addition to the default behavior, it is also possible to control the number of results and starting point by passing in query parameters  as described in this [section](https://developer.paysafe.com/en/resources-and-support/pagination/).

    <a name="globalinvalidcharacters" title="Global Invalid Characters"></a>

    # Global Invalid Characters

    You must not include any of the characters in this [table](https://developer.paysafe.com/en/resources-and-support/global-invalid-characters/) as values in any of your request parameters. Object. If you do, your request will result in an error.

    <a name="isostandards" title="ISO Standards"></a>

    # ISO Standards

    ISO standards add value by providing the common business process data semantics to be used in the API based exchanges. This [section](https://developer.paysafe.com/en/resources-and-support/iso-standards/) presents you codes for four areas - Currency, Province, State, and Country.

    # API

    The User Identity verification (AML assist) using verifiedme/Interac API allows merchants to verify the ownership of their customers' bank accounts by having the customer provide banking credentials online.

    The following request types are supported:

    * [Verifiedme Verification](/operations/verifiedme-verifications)

    * [Verifiedme Customer Redirections](/operations/verifiedme-redirect)

    * [Verifiedme Verification Lookups](/operations/get-verifiedme-verification-id)


    **API Endpoint**

    `https://api.paysafe.com/bankaccountvalidator/v1`

    **Resource Patterns**

    |Endpoint URL                                       |Description                            |Action |
    |---                                                |---                                    |---    |
    |/verifiedme/accounts/account_id/verifications/     |Verifiedme Customer's Bank Account     |POST   |
    |/verifiedme/redirect/session_id                    |Verifiedme Redirect Account Details    |GET    |
    |/verifiedme/verifications/verification_id          |Verifiedme Get Bank Account Details    |GET    |


    # Legal and Community

    <ul> 
    <li><a href="https://www.paysafe.com/paysafegroup/privacy-policy/" target="_blank">Privacy Policy</a></li>
    <li><a href="https://developer.paysafe.com/en/resources-and-support/terms-of-use/" target="_blank">Terms of Use</a></li>
    <li><a href="https://www.paysafe.com/paysafegroup/regulatory-disclosures/" target="_blank">Regulatory Disclosures</a></li>
    </ul>
  contact: {}
  version: '1.0'
servers:
  - url: 'https://api.test.paysafe.com/bankaccountvalidator/'
    variables: {}
  - url: ''
    description: ''
paths:
  /v1/monitor:
    get:
      summary: Verify That the Service Is Accessible
      description: |-
        <a name="verifyservice" title="Verify Service"></a>

        This call returns a status of READY if the API is available.
      operationId: verify-service-accessible
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/verifyThattheServiceIsAccessibleresponse'
                  - example:
                      status: READY
              example:
                status: READY
      deprecated: false
      x-internal: false
  '/v1/verifiedme/accounts/{accountId}/verifications':
    parameters:
      - schema:
          type: string
        name: accountId
        in: path
        required: true
        description: This is the merchant account number.
    post:
      summary: Create Verifiedme Verification
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    id: b586034f-5984-4a16-a09e-adbbd98d22de
                    sessionId: MzdhM2U5NTUtYWQ2Yi00MGU1LWIzZjQtNjRkYTEyYzUxYTRh
                    links:
                      - rel: redirect_bank_validation
                        href: 'https://api.test.paysafe.com/bankaccountvalidator/v1/verifiedme/redirect?sessionId=MzdhM2U5NTUtYWQ2Yi00MGU1LWIzZjQtNjRkYTEyYzUxYTRh'
                    status: INITIATED
                    merchantRefNum: testRefNum
                    returnLinks:
                      - rel: default
                        href: 'https://mysite.com/return'
                    metadata:
                      key1: value1
                      key2: value2
                properties:
                  id:
                    type: string
                    description: 'This is the ID returned in the response. This ID can be used for future associated requests, e,g., to look up the bank account verification details.'
                  sessionId:
                    type: string
                    description: This is the encoded ID that will be used in the API request to redirect the customer to the bank account validation page. This ID is valid for 10 minutes.
                  links:
                    type: array
                    description: |
                      To navigate to the vendor’s UI where online banking.

                      "links": [
                          {
                            "rel": "redirect_bank_validation",
                            "href": "https://api.paysafe.com/bankaccountvalidator/v1/verifiedme/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz"
                          }
                        ]
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                          description: This is the link to the endpoint at the end of the transaction.
                        href:
                          type: string
                  status:
                    description: |-
                      This shows the status of the bank account verification request.

                      Read Only
                    type: string
                  merchantRefNum:
                    type: string
                    description: This is the same merchant ref number echoed back from the request.
                  returnLinks:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                          description: This is the link type and default vaule is "redirect_bank_validation"
                        href:
                          type: string
                          description: The Online banking pages to which the customer will be redirected where list of banks will be presented to customer to select and enter online banking credentials.
                  metadata:
                    type: object
                    properties:
                      key1:
                        type: string
                        description: Same value echoed back from request.
                      key2:
                        type: string
                        description: Same value echoed back from request.
                  scopeType:
                    type: string
                    description: |-
                      This is an enum, determining the UI flow of the merchant while bank verification.
                      Possible values as below:
                      |Status|Description|
                      |---|---|
                      |DOCVERIFICATIONSCOPE |When this is selected as scope then the new flow of user uploading the required documents for verification will be invoked.|
                      |VERIFIEDMESCOPE | When user passes this as scope type then the invocation of the amlassist for the bank verification happens. 
                    default: DOCVERIFICATIONSCOPE
                    example: DOCVERIFICATIONSCOPE
              examples:
                example-1:
                  value:
                    id: string
                    sessionId: string
                    links:
                      - rel: string
                        href: string
                    status: string
                    merchantRefNum: string
                    returnLinks:
                      - rel: string
                        href: string
                    metadata:
                      key1: string
                      key2: string
                    scopeType: DOCVERIFICATIONSCOPE
                example-2:
                  value:
                    merchantRefNum: '1323563'
                    returnLinks:
                      - rel: default
                        href: 'https://mysite.com/return'
                    id: 6a275b7c-6f11-4ed1-ae77-21071724574a
                    sessionId: MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz
                    status: INITIATED
                    links:
                      - rel: redirect_bank_validation
                        href: 'https://api.paysafe.com/bankaccountvalidator/v1/verifiedme/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz'
                    metadata:
                      customerId: '879389846335'
                    scopeType: VERIFIEDMESCOPE
      operationId: verifiedme-verifications
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          style: simple
          schema:
            enum:
              - application/json
            type: string
            example: application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  merchantRefNum: '1323563'
                  accountId: '123456789'
                  returnLinks:
                    - rel: default
                      href: 'https://mysite.com/return'
              properties:
                merchantRefNum:
                  type: string
                  description: This is the merchant reference number created by the merchant and submitted as part of the request.
                accountId:
                  type: string
                  description: This is the merchant account number.
                returnLinks:
                  type: array
                  description: |
                    The URL endpoint to redirect the consumer to.
                     You can customize the return URL based on the transaction status. 
                    The 'default' value is mandatory.

                    Options:
                    • default - The default return URL, which will be used if specific status return URL is not defined.
                    • on_completed - It will be Used in case of successful bank account validation.
                    • on_failed - It will be used in case of Unsuccessfulbank account validation.
                  items:
                    type: object
                    properties:
                      rel:
                        type: string
                        description: 'This is the link type, allowing different endpoints to be targeted depending on the end state of the transaction. The link relation describes how this link relates to the previous call.'
                      href:
                        type: string
                        description: The actual URL to which the customer will be redirected.
                locale:
                  type: string
                  description: "To identify the locale and present the UI in desired language. \nIf opted locale is not available default would be en_CA. \nRefer locale table below for list of locales.\n\n|Locale to be passed in request|Locale Description|\n|---|---|\n|en_CA |English (Canada)|\n|fr_CA  |French (Canada)\n|bg\t|Bulgarian\n|cz\t|Czech\n|de\t|German\n|de_AT\t|German (Austria)\n|da\t|Danish\n|no\t|Norwegian\n|sv\t|Swedish\n|en\t|English\n|es_MX |Spanish (Mexico)\n|es\t|Spanish\n|fr\t|French\n|he\t|Hebrew\n|it\t|Italian\n|nl\t|Dutch\n|pl\t|Polish\n|pt_BR |Portuguese (Brazil)\n|pt\t|Portuguese\n|ro\t|Romanian\n|ru\t|Russian\n|sk\t|Slovak\n|tr\t|Turkish\n|uk\t|Ukrainian\n|zh_HK\t|Chinese (Hong Kong)\n|zh\t|Chinese\n|hu\t|Hungarian\n\n"
                metadata:
                  type: object
                scopeType:
                  type: string
                  description: |-
                    This is an enum, determining the UI flow of the merchant while bank verification.
                    Possible values as below:
                    |Status|Description|
                    |---|---|
                    |DOCVERIFICATIONSCOPE |When this is selected as scope then the new flow of user uploading the required documents for verification will be invoked.|
                    |VERIFIEDMESCOPE | When user passes this as scope type then the invocation of the amlassist for the bank verification happens.                            
                  default: DOCVERIFICATIONSCOPE
                  example: DOCVERIFICATIONSCOPE
            examples:
              Sample format:
                value:
                  merchantRefNum: string
                  accountId: string
                  returnLinks:
                    - rel: string
                      href: string
                  locale: string
                  metadata:
                    key: value
                  scopeType: DOCVERIFICATIONSCOPE
              example-1:
                value:
                  merchantRefNum: '1323563'
                  accountId: PMLE100
                  locale: en_CA
                  returnLinks:
                    - rel: default
                      href: 'https://mysite.com/return'
                  metadata:
                    customerId: '879389846335'
                  scopeType: VERIFIEDMESCOPE
        description: ''
      description: This Api will initiate a session at Paysafe side for Customer’s Identity Verification and responds with a redirect URL.
  /v1/verifiedme/redirect:
    parameters:
      - schema:
          type: string
        name: sessionId
        in: query
        required: true
        description: Session Id from the Initiate Verification Call
    get:
      summary: Redirect to Verifiedme
      tags: []
      responses:
        '302':
          description: Found
      operationId: verifiedme-redirect
      description: This Api can help to redirect to Interac® Verification Service's UI screens.
  '/v1/verifiedme/verifications/{verificationId}':
    parameters:
      - schema:
          type: string
        name: verificationId
        in: path
        required: true
        description: Id from the Create Verification Response.
    get:
      summary: Lookup for verifiedme user info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    merchantRefNum: corstest300
                    returnLinks:
                      - rel: default
                        href: 'https://www.google.com'
                    links:
                      - rel: redirect_bank_validation
                        href: 'https://api.qa.paysafe.com/bankaccountvalidator/v1/verifiedme/redirect?sessionId=N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk'
                    id: dc410576-c5d1-4aea-b13b-da040db028b0
                    sessionId: N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk
                    status: SUCCESS
                    userInfo:
                      addresses:
                        - country: CA
                          streetAddress: 676 RUE FOURNIER
                          addressType: CA
                          locality: SLLE
                          postalCode: J7E 3K9
                          region: QC
                      birthdate: '1933-08-01'
                      singleSource: true
                      dualSource: false
                      singleSourceDecision: true
                      dualSourceDecision: false
                      uniqueNumber: '0059465419'
                      givenName: ISABELLE
                      familyName: CORREIA
                      ageOfCreditFile3yMoreOlder: true
                      tradelines:
                        - addressProvinceMatch: 'YES'
                          middleNameMatch: NOT PROVIDED
                          addressPostalCodeMatch: 'YES'
                          lastNameMatch: 'YES'
                          firstNameMatch: 'YES'
                          addressAsReported: '676,RUE FOURNIER,ST-THER-BLAIN,QC,J7E3K9'
                          suffixNameMatch: NOT PROVIDED
                          dateOfBirthMatch: 'YES'
                          addressCityMatch: 'YES'
                          dobAsReported: '1933-08-01'
                          addressStreetNameMatch: 'YES'
                          nameAsReported: 'CORREIA,ISABELLE,C,'
                          addressCivicMatch: 'YES'
                      decision: SUCCESS
                properties:
                  merchantRefNum:
                    type: string
                    description: |
                      This is the same merchant ref number provided in the create verification request.
                  returnLinks:
                    type: array
                    description: |
                      This is the same return links echoed back from the create verification request.
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                          description: This is the type of the link and is same as in the create verification request.
                        href:
                          type: string
                          description: This is the actual link and is same as in the create verification request.
                  links:
                    type: array
                    description: The same links provided in the create verification response.
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
                  id:
                    type: string
                    description: The verification Id which is provided in the create verification response.
                  sessionId:
                    type: string
                    description: The same session Id provided in the create verification response.
                  status:
                    type: string
                    description: |-
                      The status of this transaction.
                      Possible transaction statuses below:
                      |Status|Description|
                      |---|---|
                      |INPROGRESS |The user has started the journey and dropped/cancelled in middle|
                      |SUCCESS |User completed the journey, and the user information retrieval is successful|
                      |FAILED |Failed to retrieve user information from verified.me
                  Info:
                    oneOf:
                      - $ref: '#/components/schemas/userInfo'
                      - $ref: '#/components/schemas/documentInfo'
              examples:
                Sample response for VERIFIEDMESCOPE:
                  value:
                    merchantRefNum: corstest300
                    returnLinks:
                      - rel: default
                        href: 'https://www.google.com'
                    links:
                      - rel: redirect_bank_validation
                        href: 'https://api.qa.paysafe.com/bankaccountvalidator/v1/verifiedme/redirect?sessionId=N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk'
                    id: dc410576-c5d1-4aea-b13b-da040db028b0
                    sessionId: N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk
                    status: SUCCESS
                    userInfo:
                      addresses:
                        - country: CA
                          streetAddress: 676 RUE FOURNIER
                          addressType: CA
                          locality: SLLE
                          postalCode: J7E 3K9
                          region: QC
                      birthdate: '1933-08-01'
                      singleSource: true
                      dualSource: false
                      singleSourceDecision: true
                      dualSourceDecision: false
                      uniqueNumber: '0059465419'
                      givenName: ISABELLE
                      familyName: CORREIA
                      ageOfCreditFile3yMoreOlder: true
                      tradelines:
                        - addressProvinceMatch: 'YES'
                          middleNameMatch: NOT PROVIDED
                          addressPostalCodeMatch: 'YES'
                          lastNameMatch: 'YES'
                          firstNameMatch: 'YES'
                          addressAsReported: '676,RUE FOURNIER,ST-THER-BLAIN,QC,J7E3K9'
                          suffixNameMatch: NOT PROVIDED
                          dateOfBirthMatch: 'YES'
                          addressCityMatch: 'YES'
                          dobAsReported: '1933-08-01'
                          addressStreetNameMatch: 'YES'
                          nameAsReported: 'CORREIA,ISABELLE,C,'
                          addressCivicMatch: 'YES'
                      decision: SUCCESS
                Sample response for DOCVERIFICATIONSCOPE:
                  value:
                    merchantRefNum: corstest300
                    returnLinks:
                      - rel: default
                        href: 'https://www.google.com'
                    links:
                      - rel: redirect_bank_validation
                        href: 'https://api.qa.paysafe.com/bankaccountvalidator/v1/verifiedme/redirect?sessionId=N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk'
                    id: dc410576-c5d1-4aea-b13b-da040db028b0
                    sessionId: N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk
                    status: SUCCESS
                    documentInfo:
                      address:
                        country: CAN
                        locality: North York
                        postal_code: M2P 1N6
                        region: 'ON'
                        street_address: 4101 Yonge St
                      birthdate: '1990-01-31'
                      com.securekey.verified.me.ui_locale: en-CA
                      com.securekey.vids.job_id: 501640cd-d22d-4e5c-875e-ea7df054e9bd
                      doc_number: S12345678901234
                      doc_type: drivers_license
                      expiry_date: '2030-01-31'
                      family_name: DOE
                      given_name: JANE H
                      issue_date: '2020-10-21'
                      issuing_authority: 'ON'
                      issuing_country: CA
                      nationality: N/A
                      scan_result: CLEAR
                      source: driving_licence
                      sub: 501640cd-d22d-4e5c-875e-ea7df054e9bd
                Suspected response:
                  value:
                    merchantRefNum: corstest300
                    returnLinks:
                      - rel: default
                        href: 'https://www.google.com'
                    links:
                      - rel: redirect_bank_validation
                        href: 'https://api.qa.paysafe.com/bankaccountvalidator/v1/verifiedme/redirect?sessionId=N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk'
                    id: dc410576-c5d1-4aea-b13b-da040db028b0
                    sessionId: N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk
                    status: SUCCESS
                    documentInfo:
                      sub: fd43f0ed-db74-46af-8f35-2e16c78308e3
                      address:
                        country: N/A
                        street_address: N/A
                        locality: N/A
                        postal_code: N/A
                        region: N/A
                      birthdate: '1958-07-02'
                      com.securekey.verified.me.ui_locale: en-CA
                      expiry_date: '2024-09-04'
                      doc_number: GA302922
                      suspected_flags:
                        - face_match
                        - spoofing_detection
                      doc_type: passport
                      source: passport
                      given_name: JOHN TIM
                      com.securekey.vids.job_id: fd43f0ed-db74-46af-8f35-2e16c78308e3
                      scan_result: CLEAR
                      issue_date: '2014-09-04'
                      nationality: CAN
                      issuing_country: CA
                      issuing_authority: CA
                      family_name: NET
                Rejected response:
                  value:
                    merchantRefNum: corstest300
                    returnLinks:
                      - rel: default
                        href: 'https://www.google.com'
                    links:
                      - rel: redirect_bank_validation
                        href: 'https://api.qa.paysafe.com/bankaccountvalidator/v1/verifiedme/redirect?sessionId=N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk'
                    id: dc410576-c5d1-4aea-b13b-da040db028b0
                    sessionId: N2U5N2QyN2ItOWJkMi00NjliLWI0NWMtMmFhZWQ1MzBjMmVk
                    status: REJECTED
                    documentInfo:
                      sub: e54d47c8-1f03-4ab6-b471-15cf926684db
                      address:
                        country: N/A
                        street_address: N/A
                        locality: N/A
                        postal_code: N/A
                        region: N/A
                      birthdate: '2000-12-25'
                      com.securekey.verified.me.ui_locale: en-CA
                      expiry_date: '2000-12-25'
                      doc_number: GC000000
                      suspected_flags:
                        - visual_authenticity
                        - data_consistency
                        - data_validation
                        - spoofing_detection
                      doc_type: passport
                      source: passport
                      given_name: CLAUS
                      com.securekey.vids.job_id: e54d47c8-1f03-4ab6-b471-15cf926684db
                      scan_result: REJECTED
                      issue_date: '2000-12-25'
                      nationality: CAN
                      issuing_country: CA
                      issuing_authority: CA
                      family_name: SANTA
                      rejected_flags:
                        - document_expiration
      operationId: get-verifiedme-verification-id
      description: |-
        The Paysafe Fetch User Information from Identity Verification API allows a merchant to fetch the user information from a customer's bank account by prompting the customer to enter their online banking credentials via a user interface presented by Interac. Once the customer has verified that they own the bank account, the merchant can then proceed to fetch the corresponding user's information.

        The response of this API varies, based on the scopeType which is selected during the verification initiation phase.
components:
  schemas:
    links:
      title: links
      type: object
      properties:
        rel:
          type: string
          description: 'This is the link type, allowing different endpoints to be targeted depending on the end state of the request.'
          example: redirect_bank_validation
        href:
          type: string
          description: 'The actual URL to which the customer will be redirected, e.g., a redirect for bank account validation.'
          example: 'https://api.paysafe.com/bankaccountvalidator/v1/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz'
      x-internal: false
      x-stoplight:
        id: bf8418aa6e752
    linksVerification:
      title: linksVerification
      type: object
      properties:
        returnLinks:
          type: array
          items:
            $ref: '#/components/schemas/links'
          description: |-
            This is an array of links related to the resource.

            Typically you will have reference to any parent resources, and a reference to the child resource (if applicable).
            You may also see links for any call to action flows.
          readOnly: true
      x-internal: true
      x-stoplight:
        id: cd78cb38beb84
    returnLinksLookup:
      title: returnLinksLookup
      type: object
      properties:
        returnLinks:
          allOf:
            - $ref: '#/components/schemas/returnLinkUrl'
            - description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status.
              readOnly: true
      x-examples:
        Example 1:
          returnLinks:
            rel: default
            href: string
      x-internal: true
      x-stoplight:
        id: 5364fff57f080
    locale:
      title: locale
      enum:
        - en_CA
        - fr_CA
      type: string
      description: This indicates the language of the user interface.
      example: en_CA
      x-internal: true
      x-examples:
        example-1: en_CA
    rel:
      title: rel
      enum:
        - default
        - on_completed
        - on_failed
      type: string
      description: 'This is the link type, allowing different endpoints to be targeted depending on the end state of the transaction. The link relation describes how this link relates to the previous call.'
      x-internal: true
    returnLinkUrl:
      title: returnLinkUrl
      type: object
      properties:
        rel:
          allOf:
            - $ref: '#/components/schemas/rel'
            - description: 'This is the link type, allowing different endpoints to be targeted depending on the end state of the transaction. The link relation describes how this link relates to the previous call.'
        href:
          type: string
          description: The actual URL to which the customer will be redirected.
          example: 'https://mysite.com/return'
      description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status.
      readOnly: true
      x-internal: true
      x-examples:
        Example 1:
          rel: default
          href: 'https://mysite.com/return'
      x-stoplight:
        id: d05692847ec0a
    returnLinks:
      title: returnLinks
      type: object
      x-internal: false
      x-stoplight:
        id: 889af722fc791
      properties:
        returnLinks:
          type: array
          description: |-
            This is an array of links related to the resource.

            Typically you will have reference to any parent resources, and a reference to the child resource (if applicable).
            You may also see links for any call to action flows.
          readOnly: true
          items:
            $ref: '#/components/schemas/returnLinkUrl'
      x-examples:
        Example 1:
          returnLinks:
            - rel: default
              href: 'https://mysite.com/return'
      description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status.
    defaultReturnLinks:
      title: defaultReturnLinks
      required:
        - rel
        - href
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
      example:
        rel: default
        href: 'https://mysite.com/return'
      x-stoplight:
        id: 61c3edf53fad0
      x-internal: true
    status:
      title: status
      enum:
        - SUCCESS
        - FAILED
        - INITIATED
        - INCOMPLETE
      type: string
      description: This shows the status of the bank account verification request.
      readOnly: true
      example: INITIATED
      x-internal: true
    verifyThattheServiceIsAccessibleresponse:
      title: verifyThattheServiceIsAccessibleresponse
      required:
        - status
      type: object
      properties:
        status:
          type: string
      example:
        status: READY
      x-internal: true
      x-stoplight:
        id: 1080ea5dc733e
    userInfo:
      type: object
      x-examples:
        Example 1:
          addresses:
            - country: CA
              streetAddress: 676 RUE FOURNIER
              addressType: CA
              locality: SLLE
              postalCode: J7E 3K9
              region: QC
          birthdate: '1933-08-01'
          singleSource: true
          dualSource: false
          singleSourceDecision: true
          dualSourceDecision: false
          uniqueNumber: '0059465419'
          givenName: ISABELLE
          familyName: CORREIA
          ageOfCreditFile3yMoreOlder: true
          tradelines:
            - addressProvinceMatch: 'YES'
              middleNameMatch: NOT PROVIDED
              addressPostalCodeMatch: 'YES'
              lastNameMatch: 'YES'
              firstNameMatch: 'YES'
              addressAsReported: '676, RUE FOURNIER, ST-THER-BLAIN, QC, J7E3K9'
              suffixNameMatch: NOT PROVIDED
              dateOfBirthMatch: 'YES'
              addressCityMatch: 'YES'
              dobAsReported: '1933-08-01'
              addressStreetNameMatch: 'YES'
              nameAsReported: 'CORREIA, ISABELLE, C,'
              addressCivicMatch: 'YES'
      description: This is the user info object.
      properties:
        addresses:
          type: array
          description: Addresses of the Fecthed user.
          items:
            type: object
            properties:
              country:
                type: string
                description: country code
              streetAddress:
                type: string
                description: street address in a standard canadian format
              addressType:
                type: string
                description: Address Type
              locality:
                type: string
                description: Locality of this address.
              postalCode:
                type: string
                description: Postal code of this address
              region:
                type: string
                description: Region of this address
        birthdate:
          type: string
          description: This is the customer's date of birth
        singleSource:
          type: boolean
          description: This indicates whether the single source product has been used.
        dualSource:
          type: boolean
          description: This indicates whether the dual source product has been used.
        singleSourceDecision:
          type: boolean
          description: This is the result of the decisioning model for the single source product.
        dualSourceDecision:
          type: boolean
          description: This is the result of the decisioning model for the dual source product.
        uniqueNumber:
          type: string
          description: This is the credit file number received from the downstream provider.
        givenName:
          type: string
          description: This is the given name retrieved from the verifiedme output.
        familyName:
          type: string
          description: This is the family name retrieved from the verifiedme output.
        ageOfCreditFile3yMoreOlder:
          type: boolean
          description: This indicates whether the credit file is greater than three years old.
        tradelines:
          type: array
          items:
            type: object
            properties:
              addressProvinceMatch:
                type: string
                description: |-
                  This indicates whether the address province matched.
                  Possible Values : YES / NO / NOT PROVIDED
              middleNameMatch:
                type: string
                description: |-
                  This indicates whether the middle name matched.
                  Possible Values : YES / NO / NOT PROVIDED
              addressPostalCodeMatch:
                type: string
                description: |-
                  This indicates whether the address postal code matched.
                  Possible Values : YES / NO / NOT PROVIDED
              lastNameMatch:
                type: string
                description: |-
                  This indicates whether the last name matched.
                  Possible Values : YES / NO / NOT PROVIDED 
              firstNameMatch:
                type: string
                description: |-
                  This indicates whether the first name matched.
                  Possible Values : YES / NO / NOT PROVIDED
              addressAsReported:
                type: string
                description: This is the address retrieved from the downstream provider output.
              suffixNameMatch:
                type: string
                description: |-
                  This indicates whether the suffix name matched
                  Possible Values : YES / NO / NOT PROVIDED
              dateOfBirthMatch:
                type: string
                description: |-
                  This indicates whether the date of birth matched.
                  Possible Values : YES / NO / NOT PROVIDED
              addressCityMatch:
                type: string
                description: |-
                  This indicates whether the address city matched.
                  Possible Values : YES / NO / NOT PROVIDED
              dobAsReported:
                type: string
                description: This is the date of birth retrieved from the downstream provider output.
              addressStreetNameMatch:
                type: string
                description: |-
                  This indicates whether the address street name matched
                  Possible Values : YES / NO / NOT PROVIDED
              nameAsReported:
                type: string
                description: This is the name retrieved from the downstream provider output.
              addressCivicMatch:
                type: string
                description: |-
                  This indicates whether the civic number of the address matched.
                  Possible Values : YES / NO / NOT PROVIDED
        decision:
          type: string
          description: |-
            Over All Decision calculated based on below matrix
            |Single Source|Single Source Decision|Dual Source|Dual Source Decision|Final Status|
            |---|---|---|---|---|
            |Credit file found |Fail|Trade info found|Fail|FAIL|
            |Credit file found |Fail|Trade info found|Success|SUCCESS|
            |Credit file found |Success|Trade info not found|Fail|SUCCESS|
            |Credit file not found|Fail|Trade info found|Fail|FAIL|
            |Credit file not found|Fail|Trade info found|Success|SUCCESS|
            |Credit file not found|Fail|Trade info not found|Fail|FAIL|   
    documentInfo:
      type: object
      x-examples:
        Example 1:
          sub: fd43f0ed-db74-46af-8f35-2e16c78308e3
          address:
            country: N/A
            street_address: N/A
            locality: N/A
            postal_code: N/A
            region: N/A
          birthdate: '1958-07-02'
          com.securekey.verified.me.ui_locale: en-CA
          expiry_date: '2024-09-04'
          doc_number: GA302922
          suspected_flags:
            - face_match
            - spoofing_detection
          doc_type: passport
          source: passport
          given_name: JOHN TIM
          com.securekey.vids.job_id: fd43f0ed-db74-46af-8f35-2e16c78308e3
          scan_result: CLEAR
          issue_date: '2014-09-04'
          nationality: CAN
          issuing_country: CA
          issuing_authority: CA
          family_name: NET
      description: This is the document info object.
      properties:
        sub:
          type: string
          description: This is unique id of the document.
        address:
          type: object
          description: Address of the Fecthed user.
          properties:
            country:
              type: string
              description: ' country code.'
            street_address:
              type: string
              description: street address in a standard canadian format.
            locality:
              type: string
              description: ' Locality of this address.'
            postal_code:
              type: string
              description: Postal code of this address.
            region:
              type: string
              description: Region of this address.
        birthdate:
          type: string
          description: This is the customer's date of birth.
        com.securekey.verified.me.ui_locale:
          type: string
          description: "To identify the locale and present the UI in desired language. \nIf opted locale is not available default would be en_CA. \nRefer locale table below for list of locales.\n\n|Locale to be passed in request|Locale Description|\n|---|---|\n|en_CA |English (Canada)|\n|fr_CA  |French (Canada)\n|bg\t|Bulgarian\n|cz\t|Czech\n|de\t|German\n|de_AT\t|German (Austria)\n|da\t|Danish\n|no\t|Norwegian\n|sv\t|Swedish\n|en\t|English\n|es_MX |Spanish (Mexico)\n|es\t|Spanish\n|fr\t|French\n|he\t|Hebrew\n|it\t|Italian\n|nl\t|Dutch\n|pl\t|Polish\n|pt_BR |Portuguese (Brazil)\n|pt\t|Portuguese\n|ro\t|Romanian\n|ru\t|Russian\n|sk\t|Slovak\n|tr\t|Turkish\n|uk\t|Ukrainian\n|zh_HK\t|Chinese (Hong Kong)\n|zh\t|Chinese\n|hu\t|Hungarian\n\n"
        expiry_date:
          type: string
          description: This is expiry date of the document.
        doc_number:
          type: string
          description: This is the document number issued.
        suspected_flags:
          type: array
          description: |-
            The suspected flags of the document in case of even Scan Result as CLEAR or in case of REJECTED. 
            |Status|Description |
            |---|---|
            |data_validation |One or more data elements were inconsistent with the expectations for the document: for example, values such as dates are in the wrong format. This includes the document expiration field, gender, document numbers, date of birth, and the MRZ.|
            |visual_authenticity |The visual features of the document being processed did not clear; this could be because the original document was not present (picture of a screen), there is evidence of digital tampering, or tampering/mismatch with the face picture, the fonts, or the document template.|
            |data_consistency |Data on the document in multiple places did not match (for example, printed fields and in the MZR or barcode).|
            |compromised_document |The document has been flagged as compromised. This is not an authoritative check, but from the 3rd party scanning service.|
            |source_integrity |The likelihood that the live photo source is not genuine is high (digitally tampered with or taken from a webcam etc).|
            |face_match |It indicates differences in facial comparison between the face in the live photo and the face from the document scan.|
            |spoofing_detection |The likelihood that spoofing attempts were made is high - such as taking a picture of a portrait or screenshot.
          items:
            type: string
        rejected_flags:
          type: array
          description: |-
            The rejected flags of the document in case of Scan Result as REJECTED.
            Possible flags as below:
            |Status|Description|
            |---|---|
            |image_quality |The document image was not of good enough quality to process, or not a picture of a document.|
            |conclusive_document_quality |Part of the image was obscured (like data fields or security features), the image was abnormal (overlapping data or washed-out background), the document was damaged (missing corners or punctures), there was a digital watermark, or there were not enough security features to be examined|
            |supported_document |The scanned document is not recognized as a supported document type.|
            |colour_picture |The image was NOT a color picture of a document.|
            |minimum_accepted_age |Threshold 16.|
            |data_consistency |Data on the document in multiple places did not match (for example, printed fields and in the MZR or barcode).|
            |document_expiration |The expiration date read from the document has passed or is inconsistent with other parts of the document.|
            |face_detection |No face was detected on the document.|
            |face_detected |The document portrait or the real-time photo was not of sufficient quality to get a match. This could be a damaged document, glare on the photo, or the customer did not take a proper real-time photo. This is not an indication of a deliberate attempt at fraud, more likely user error.|
            |filtered_document |The document scan was successful, but the RP's whitelist of allowed document types prohibits returning the data. For example, a Canadian Health Card was properly scanned and recognized, but the RP will only accept Driving Licenses and Passports.
          items:
            type: string
        doc_type:
          type: string
          description: |-
            The type of the document.
            Possible types as below:
            |Status|Description|
            |---|---|
            |passport |The type of the document is passport.|
            |driving_license |The type of the document is driving license.
        source:
          type: string
          description: |-
            The source of the document.
            Possible sources as below:
            |Status|Description|
            |---|---|
            |passport |The source of the document is of passport type|
            |driving_license |The source of the document is of driving license type.
        given_name:
          type: string
          description: This is the given name retrieved from the verifiedme output.
        com.securekey.vids.job_id:
          type: string
          description: This is the job id.
        scan_result:
          type: string
          description: |-
            The scan result of the document.
            Possible scan results as below:
            |Status|Description|
            |---|---|
            |CLEAR |The document retrieved is clear and its verified|
            |REJECTED |The document retrieved is not clear and its rejected.
        issue_date:
          type: string
          description: This is the issued date of document.
        nationality:
          type: string
          description: This is the nationality of the user.
        issuing_country:
          type: string
          description: This is the issuing country of the document.
        issuing_authority:
          type: string
          description: This is the issuing authority of the document.
        family_name:
          type: string
          description: This is the family name retrieved from the verifiedme output.
  securitySchemes:
    httpBasic:
      type: http
      scheme: basic
security:
  - httpBasic: []
tags: []
