openapi: 3.0.0
info:
  title: Paysafe Bank Account Validation API
  description: |-
    # Release Notes

    | Version   | Date          | Details |
    |---        |---            |---      |
    | 1.0       | April 2019    | <ul><li>Document Release</li></ul> |

    <a name="apikey" title="Authentication"></a>

    # Authentication

    In order for you to use the Paysafe REST API, Paysafe must first set you up on their system and provide you with an API key. Your API key looks something like this:

    * Key Username – MerchantXYZ

    * Key Password – B-tst1-0-51ed39e4-312d02345d3f123120881dff9bb4020a89e8ac44cdfdcecd702151182fdc952272661d290ab2e5849e31bb03deede7e

    Note this is not the same as your Merchant Back Office username and password.
    The case-sensitive API key is sent using HTTP Basic Authentication. To use HTTP Basic Authentication, you must send the API key credentials using the Authorization header with every request. The Authorization header is constructed as follows:

    1. The Key Username and Key Password are combined into a string separated by a colon, e.g.,“Key Username:Key Password”.

    2. The resulting string literal is then encoded using Base64.

    3. The authorization method and a space (i.e., “Basic”) are then put before the encoded string.

    For example, using the Key Username and Password examples above, the header is formed as follows:

    ``Authorization: Basic
    TWVyY2hhbnRYWVo6Qi10c3QxLTAtNTFlZDM5ZTQtMzEyZDAyMzQ1ZDNmMTIzMTIwODgxZGZmOWJiNDAyMGE4OWU4YWM0NGNkZmRjZWNkNzAyMTUxMTgyZmRjOTU yMjcyNjYxZDI5MGFiMmU1ODQ5ZTMxYmIwM2RlZWRlN2U=``

    For additional details, please refer to [http://en.wikipedia.org/wiki/Basic_access_authentication](http://en.wikipedia.org/wiki/Basic_access_authentication).

    **Note:** Your Production API key will be different from your Test API key. Contact your account manager for details. You must keep your API keys safe and ensure that it is used appropriately for your needs.

    # URLs

    ##  Test URL

    In order to test your integration with Paysafe, use the following Test URL:

    `https://api.test.paysafe.com`

    For example:

    `https://api.test.paysafe.com/bankaccountvalidator/v1/accounts/{account_id}/verifications`

    ## Production URL

    In order to process live requests with Paysafe, use the following Production URL:

    `https://api.paysafe.com`

    For example:

    `https://api.paysafe.com/bankaccountvalidator/v1/accounts/{account_id}/verifications`

    # Pagination

    In the case where an API GET request returns multiple results, Paysafe returns the first 10 records by default and uses HATEOAS links to provide page navigation. In addition to the default behavior, it is also possible to control the number of results and starting point by passing in query parameters  as described in this [section](https://developer.paysafe.com/en/resources-and-support/pagination/).

    <a name="globalinvalidcharacters" title="Global Invalid Characters"></a>

    # Global Invalid Characters

    You must not include any of the characters in this [table](https://developer.paysafe.com/en/resources-and-support/global-invalid-characters/) as values in any of your request parameters. Object. If you do, your request will result in an error.

    <a name="isostandards" title="ISO Standards"></a>

    # ISO Standards

    ISO standards add value by providing the common business process data semantics to be used in the API based exchanges. This [section](https://developer.paysafe.com/en/resources-and-support/iso-standards/) presents you codes for four areas - Currency, Province, State, and Country.

    # API

    The Bank Account Validation API allows merchants to verify the ownership of their customers' bank accounts by having the customer provide banking credentials online.

    The following request types are supported:

    * [Verifications](/operations/createa-verification)

    * [Customer Redirections](/operations/redirect-the-customer)

    * [Verification Lookups](/operations/get-verification)


    **API Endpoint**

    `https://api.paysafe.com/bankaccountvalidator/v1`

    **Resource Patterns**

    |Endpoint URL                                       |Description                            |Action |
    |---                                                |---                                    |---    |
    |/accounts/account_id/verifications                 |Verify a Customer's Bank Account       |POST   |
    |/redirect?session_id                               |Redirect a Customer to Validation UI   |GET    |
    |/accounts/account_id/verifications/verification_id |Get Bank Account Details               |GET    |


    # Legal and Community

    <ul> 
    <li><a href="https://www.paysafe.com/paysafegroup/privacy-policy/" target="_blank">Privacy Policy</a></li>
    <li><a href="https://developer.paysafe.com/en/resources-and-support/terms-of-use/" target="_blank">Terms of Use</a></li>
    <li><a href="https://www.paysafe.com/paysafegroup/regulatory-disclosures/" target="_blank">Regulatory Disclosures</a></li>
    </ul>
  contact: {}
  version: '1.0'
servers:
  - url: 'https://api.test.paysafe.com/bankaccountvalidator/'
    variables: {}
  - url: ''
    description: ''
paths:
  /v1/monitor:
    get:
      summary: Verify That the Service Is Accessible
      description: |-
        <a name="verifyservice" title="Verify Service"></a>

        This call returns a status of READY if the API is available.
      operationId: verify-service-accessible
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/verifyThattheServiceIsAccessibleresponse'
                  - example:
                      status: READY
              example:
                status: READY
      deprecated: false
      x-internal: false
  '/v1/accounts/{account_id}/verifications':
    post:
      summary: Create a Verification
      description: |-
        <a name="verifications" title="Verifications"></a><a name="verificationrequest" title="Verification Request"></a>

        Click on **Create a Verification** above to see how to send a bank account verification request to Paysafe.
      operationId: createa-verification
      parameters:
        - name: account_id
          in: path
          description: This is the merchant account number.
          required: true
          style: simple
          schema:
            type: string
            example: '123456789'
        - name: Content-Type
          in: header
          description: ''
          required: true
          style: simple
          schema:
            enum:
              - application/json
            type: string
            example: application/json
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request'
        required: true
      responses:
        '201':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/createaVerificationresponse'
                  - example:
                      merchantRefNum: '1323563'
                      profile:
                        firstName: Praveen
                        middleName: Kumar
                        lastName: Jain
                        locale: en_CA
                      accountTypes:
                        - SAVING
                        - CHEQUING
                      currencyCodes:
                        - CAD
                        - USD
                      returnLinks:
                        - rel: default
                          href: 'https://mysite.com/return'
                      bankScheme: ACH
                      id: 6a275b7c-6f11-4ed1-ae77-21071724574a
                      sessionId: MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz
                      status: INITIATED
                      links:
                        - rel: redirect_bank_validation
                          href: 'https://api.paysafe.com/bankaccountvalidator/v1/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz'
              example:
                merchantRefNum: '1323563'
                profile:
                  firstName: Praveen
                  middleName: Kumar
                  lastName: Jain
                  locale: en_CA
                accountTypes:
                  - SAVING
                  - CHEQUING
                currencyCodes:
                  - CAD
                  - USD
                returnLinks:
                  - rel: default
                    href: 'https://mysite.com/return'
                bankScheme: ACH
                id: 6a275b7c-6f11-4ed1-ae77-21071724576a
                sessionId: MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz
                status: INITIATED
                links:
                  - rel: redirect_bank_validation
                    href: 'https://api.paysafe.com/bankaccountvalidator/v1/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz'
      deprecated: false
  /v1/redirect:
    get:
      summary: Redirect the Customer
      description: |-
        <a name="verifications" title="Verifications"></a><a name="redirectionrequest" title="Customer Redirection Request"></a>

        Click on **Redirect the Customer** above to see how to redirect a customer so they can validate their bank account details.

        >**Note:** Because this is a redirect request, there is no synchronous response available.
      operationId: redirect-the-customer
      parameters:
        - name: sessionId
          in: query
          description: This is the *sessionId* returned in the response to the bank account verification request.
          required: true
          schema:
            type: string
            example: MmM2OGNiNWMtMWNmYS0xMWU5LWFiMTQtZDY2M2JkODczZDkz
      responses:
        '302':
          description: ''
          headers: {}
          content: {}
      deprecated: false
      security: []
  '/v1/accounts/{account_id}/verifications/{verification_id}':
    get:
      summary: Get Verification
      description: "<a name=\"verifications\" title=\"Verifications\"></a><a name=\"getverification\" title=\"Look Up a Verification\"></a>\n\nOnce the customer has selected a bank account, Paysafe sends a Final Response to the URL\_you provided in the *returnLinks* object in the Create a Verification request. \nThis response notifies you that the customer successfully verified their bank account.\n\nClick on **Get Verification** above to see how to look up a Verification request using the ID returned in the response to the original Create a Verification request.\n\nThe response to the Get Verification request will include the customer's bank account details, including a single-use *paymentToken* that is valid for 15 minutes. \nYou can use this  payment token for several request types in the Paysafe APIs, including:\n\n* [Process a Standalone Credit using the Paysafe Direct Debit API](https://developer.paysafe.com/en/direct-debit/api/#/reference/0/standalone-credits) to complete the customer's request to cash out to their bank account\n\n* [Create a permanent payment token in the Customer Vault API](https://developer.paysafe.com/en/vault/api/#/reference/0/eft-bank-accounts/create-an-eft-bank-account-using-a-single-use-token) that you can then use repeatedly to process requests in the Direct Debit API"
      operationId: get-verification
      parameters:
        - name: account_id
          in: path
          description: This is the merchant account number.
          required: true
          style: simple
          schema:
            type: string
            example: '123456789'
        - name: verification_id
          in: path
          description: This is the ID returned in the response to the bank account verification request.
          required: true
          style: simple
          schema:
            type: string
            example: 6a275b7c-6f11-4ed1-ae77-21071724576a
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/getVerificationresponse'
                  - example:
                      merchantRefNum: '1323563'
                      accountTypes:
                        - SAVING
                        - CHEQUING
                      currencyCodes:
                        - CAD
                        - USD
                      returnLinks:
                        - rel: default
                          href: 'https://mysite.com/return'
                      links:
                        - rel: redirect_bank_validation
                          href: 'https://api.paysafe.com/bankaccountvalidator/v1/verifications/6a275b7c-6f11-4ed1-ae77-21071724576a/redirect'
                      id: 6a275b7c-6f11-4ed1-ae77-21071724574a
                      sessionId: MmM2OGNiNWMtMWNmYS0xMWU5LWFiMTQtZDY2M2JkODczZDkz
                      status: SUCCESS
                      eft:
                        accountHolderName: John Carta
                        institutionId: '001'
                        transitNumber: '25039'
                        lastDigits: '01'
                        accountType: SAVING
                        paymentToken: 8Y9u7WR3E32EB09J
                      profile:
                        firstName: John
                        middleName: ''
                        lastName: Carter
                        locale: en_CA
              example:
                merchantRefNum: '1323563'
                accountTypes:
                  - SAVING
                  - CHEQUING
                currencyCodes:
                  - CAD
                  - USD
                returnLinks:
                  - rel: default
                    href: 'https://mysite.com/return'
                links:
                  - rel: redirect_bank_validation
                    href: 'https://api.paysafe.com/bankaccountvalidator/v1/verifications/6a275b7c-6f11-4ed1-ae77-21071724576a/redirect'
                id: 6a275b7c-6f11-4ed1-ae77-21071724576a
                sessionId: MmM2OGNiNWMtMWNmYS0xMWU5LWFiMTQtZDY2M2JkODczZDkz
                status: SUCCESS
                eft:
                  accountHolderName: John Carta
                  institutionId: '001'
                  transitNumber: '25039'
                  lastDigits: '01'
                  accountType: SAVING
                  paymentToken: 8Y9u7WR3E32EB09J
                profile:
                  firstName: John
                  middleName: ''
                  lastName: Carter
                  locale: en_CA
      deprecated: false
components:
  schemas:
    ach:
      title: ach
      type: object
      properties:
        accountHolderName:
          type: string
          description: This is the account holder's name.
          maxLength: 22
          example: Jane Smith
        routingNumber:
          type: string
          description: This is the 9-digit routing number of the customer’s bank account.
          maxLength: 9
          minLength: 9
          example: '123456789'
        accountType:
          allOf:
            - $ref: '#/components/schemas/accountType'
            - description: This is the type of the bank account.
              example: SAVING
        lastDigits:
          type: string
          description: This is the last two digits of the bank account number.
          minLength: 2
          maxLength: 2
          example: '12'
        paymentToken:
          type: string
          description: 'This is the single-use token representing the bank account. It is valid for 15 minutes, after which it expires.'
          maxLength: 50
          example: 8Y9u7WR3E32EB09J
      description: These are ACH bank account details.
    eft:
      title: eft
      type: object
      properties:
        accountHolderName:
          type: string
          description: This is the account holder's name.
          maxLength: 25
          example: Jane Smith
        institutionId:
          type: string
          description: This is the 3-digit institution ID of the customer’s bank branch.
          maxLength: 3
          minLength: 3
          example: '001'
        transitNumber:
          type: string
          description: This is the 5-digit transit number of the customer's bank branch.
          maxLength: 5
          minLength: 5
          example: '25039'
        accountType:
          allOf:
            - $ref: '#/components/schemas/accountType'
            - description: This is the type of the bank account.
              example: SAVING
        lastDigits:
          type: string
          description: This is the last two digits of the bank account number.
          maxLength: 2
          minLength: 2
          example: '15'
        paymentToken:
          type: string
          description: 'This is the single-use token representing the bank account. It is valid for 15 minutes, after which it expires.'
          readOnly: true
          maxLength: 50
          example: 8Y9u7WR3E32EB09J
      description: These are EFT bank account details.
    links:
      title: links
      type: object
      properties:
        rel:
          type: string
          description: 'This is the link type, allowing different endpoints to be targeted depending on the end state of the request.'
          example: redirect_bank_validation
        href:
          type: string
          description: 'The actual URL to which the customer will be redirected, e.g., a redirect for bank account validation.'
          example: 'https://api.paysafe.com/bankaccountvalidator/v1/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz'
      x-internal: false
      x-stoplight:
        id: bf8418aa6e752
    linksVerification:
      title: linksVerification
      type: object
      properties:
        returnLinks:
          type: array
          items:
            $ref: '#/components/schemas/links'
          description: |-
            This is an array of links related to the resource.

            Typically you will have reference to any parent resources, and a reference to the child resource (if applicable).
            You may also see links for any call to action flows.
          readOnly: true
      x-internal: true
      x-stoplight:
        id: cd78cb38beb84
    returnLinksLookup:
      title: returnLinksLookup
      type: object
      properties:
        returnLinks:
          allOf:
            - $ref: '#/components/schemas/returnLinkUrl'
            - description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status.
              readOnly: true
      x-examples:
        Example 1:
          returnLinks:
            rel: default
            href: string
      x-internal: true
      x-stoplight:
        id: 5364fff57f080
    verificationRequest:
      title: verificationRequest
      required:
        - merchantRefNum
        - returnLinks
        - bankScheme
      type: object
      properties:
        merchantRefNum:
          type: string
          description: 'This is the merchant reference number created by the merchant and submitted as part of the request.          maxLength: 255'
          example: '1323563'
        accountTypes:
          type: array
          items:
            type: string
          description: 'This is the list of bank account types that will be presented. Possible values are: SAVING, CHEQUING'
        currencyCodes:
          type: array
          items:
            type: string
          description: 'This is the currency of the bank accounts that will be presented. Possible values are: CAD, USD'
        returnLinks:
          allOf:
            - $ref: '#/components/schemas/returnLinks'
            - description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status. The 'default' value is mandatory.
        bankScheme:
          allOf:
            - $ref: '#/components/schemas/bankScheme'
            - description: This is the bank scheme for which the merchant wants to validate the account.
              example: ACH
        id:
          type: string
          description: 'This is the ID returned in the response. This ID can be used for future associated requests, e,g., to look up the bank account verification details.'
          readOnly: true
          maxLength: 36
          example: 25f6dadf-176a-415f-95c9-6ff39ff697ba
        sessionId:
          type: string
          description: 'This is the encoded ID that will be used in the [API request to redirect the customer to the bank account validation page](#redirectionrequest). This ID is valid for 10 minutes.'
          readOnly: true
          maxLength: 255
          example: MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz
        status:
          allOf:
            - $ref: '#/components/schemas/status'
            - description: This shows the status of the bank account verification request.
              readOnly: true
              example: INITIATED
        statusMessage:
          type: string
          description: This message will be returned if the *status* is FAILED or INCOMPLETE.
          readOnly: true
          maxLength: 255
          example: message
        profile:
          allOf:
            - $ref: '#/components/schemas/profile'
            - description: This is some profile information about the customer.
        links:
          type: array
          items:
            $ref: '#/components/schemas/links'
          description: |-
            This is an array of links related to the resource.

            Typically you will have reference to any parent resources, and a reference to the child resource (if applicable).
            You may also see links for any call to action flows.
          readOnly: true
      x-internal: true
      x-stoplight:
        id: b7f1bd1cfb38d
    verificationLookupRequest:
      title: verificationLookupRequest
      type: object
      properties:
        merchantRefNum:
          type: string
          description: This is the merchant reference number created by the merchant and submitted as part of the request.
          readOnly: true
          maxLength: 255
          example: P1234
        accountTypes:
          type: array
          items:
            type: string
          description: 'This is the list of bank account types that will be presented. Possible values are: SAVING, CHEQUING'
          readOnly: true
        currencyCodes:
          type: array
          items:
            type: string
          description: 'This is the currency of the bank accounts that will be presented. Possible values are: CAD, USD'
          readOnly: true
        id:
          type: string
          description: 'This is the ID returned in the response. This ID can be used for future associated requests, e,g., to look up the bank account verification details.'
          readOnly: true
          maxLength: 36
          example: 25f6dadf-176a-415f-95c9-6ff39ff697ba
        sessionId:
          type: string
          description: 'This is the encoded ID that will be used in the [API request to redirect the customer to the bank account validation page](#redirectionrequest). This ID is valid for 10 minutes.'
          readOnly: true
          maxLength: 255
          example: MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz
        status:
          allOf:
            - $ref: '#/components/schemas/status'
            - description: This shows the status of the bank account verification request.
              readOnly: true
              example: SUCCESS
        statusMessage:
          type: string
          description: This message will be returned if the *status* is FAILED or INCOMPLETE.
          readOnly: true
          maxLength: 255
          example: message
        returnLinks:
          allOf:
            - $ref: '#/components/schemas/returnLinkUrl'
            - description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status.
              readOnly: true
        links:
          type: array
          items:
            $ref: '#/components/schemas/links'
          description: |-
            This is an array of links related to the resource.

            Typically you will have reference to any parent resources, and a reference to the child resource (if applicable).
            You may also see links for any call to action flows.
          readOnly: true
        profile:
          allOf:
            - $ref: '#/components/schemas/profile'
            - description: This is some profile information about the customer.
      x-internal: true
      x-stoplight:
        id: 3accb3c8b30f5
    accountType:
      title: accountType
      enum:
        - SAVING
        - CHEQUING
      type: string
      description: This is the type of the bank account.
      example: SAVING
      x-internal: true
    bankScheme:
      title: bankScheme
      enum:
        - ACH
        - EFT
      type: string
      description: This is the bank scheme for which the merchant wants to validate the account.
      example: ACH
      x-internal: true
      x-examples:
        example-1: ACH
    createaVerificationresponse:
      title: createaVerificationresponse
      required:
        - merchantRefNum
        - profile
        - accountTypes
        - currencyCodes
        - returnLinks
        - bankScheme
        - id
        - sessionId
        - status
        - links
      type: object
      properties:
        merchantRefNum:
          type: string
        profile:
          $ref: '#/components/schemas/profile'
        accountTypes:
          type: array
          items:
            type: string
          description: ''
        currencyCodes:
          type: array
          items:
            type: string
          description: ''
        returnLinks:
          type: array
          items:
            $ref: '#/components/schemas/returnLinkUrl'
          description: ''
        bankScheme:
          type: string
        id:
          type: string
        sessionId:
          type: string
        status:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/links'
          description: ''
      example:
        merchantRefNum: '1323563'
        profile:
          firstName: Praveen
          middleName: Kumar
          lastName: Jain
          locale: en_CA
        accountTypes:
          - SAVING
          - CHEQUING
        currencyCodes:
          - CAD
          - USD
        returnLinks:
          - rel: default
            href: 'https://mysite.com/return'
        bankScheme: ACH
        id: 6a275b7c-6f11-4ed1-ae77-21071724576a
        sessionId: MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz
        status: INITIATED
        links:
          - rel: redirect_bank_validation
            href: 'https://api.paysafe.com/bankaccountvalidator/v1/redirect?sessionId=MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz'
      x-internal: true
      x-stoplight:
        id: ebc1b38c5d969
    getVerificationresponse:
      title: getVerificationresponse
      required:
        - merchantRefNum
        - accountTypes
        - currencyCodes
        - returnLinks
        - links
        - id
        - sessionId
        - status
        - eft
        - profile
      type: object
      properties:
        merchantRefNum:
          type: string
        accountTypes:
          type: array
          items:
            type: string
          description: ''
        currencyCodes:
          type: array
          items:
            type: string
          description: ''
        returnLinks:
          type: array
          items:
            $ref: '#/components/schemas/returnLinkUrl'
          description: ''
        links:
          type: array
          items:
            $ref: '#/components/schemas/links'
          description: ''
        id:
          type: string
        sessionId:
          type: string
        status:
          type: string
        eft:
          $ref: '#/components/schemas/eft'
        profile:
          $ref: '#/components/schemas/profile'
      example:
        merchantRefNum: '1323563'
        accountTypes:
          - SAVING
          - CHEQUING
        currencyCodes:
          - CAD
          - USD
        returnLinks:
          - rel: default
            href: 'https://mysite.com/return'
        links:
          - rel: redirect_bank_validation
            href: 'https://api.paysafe.com/bankaccountvalidator/v1/verifications/6a275b7c-6f11-4ed1-ae77-21071724576a/redirect'
        id: 6a275b7c-6f11-4ed1-ae77-21071724576a
        sessionId: MmM2OGNiNWMtMWNmYS0xMWU5LWFiMTQtZDY2M2JkODczZDkz
        status: SUCCESS
        eft:
          accountHolderName: John Carta
          institutionId: '001'
          transitNumber: '25039'
          lastDigits: '01'
          accountType: SAVING
          paymentToken: 8Y9u7WR3E32EB09J
        profile:
          firstName: John
          middleName: ''
          lastName: Carter
          locale: en_CA
      x-internal: true
      x-stoplight:
        id: f1d58ef892717
    locale:
      title: locale
      enum:
        - en_CA
        - fr_CA
      type: string
      description: This indicates the language of the user interface.
      example: en_CA
      x-internal: true
      x-examples:
        example-1: en_CA
    profile:
      title: profile
      required:
        - firstName
        - lastName
      type: object
      properties:
        firstName:
          type: string
          description: This is the customer's first name.
          maxLength: 80
          example: Jane
        middleName:
          type: string
          description: This is the customer's middle name.
          maxLength: 80
          example: Ellen
        lastName:
          type: string
          description: This is the customer's last name.
          maxLength: 80
          example: Smith
        locale:
          allOf:
            - $ref: '#/components/schemas/locale'
            - description: This indicates the language of the user interface.
              example: en_CA
      description: This is some profile information about the customer.
      x-stoplight:
        id: ed551505e586e
    rel:
      title: rel
      enum:
        - default
        - on_completed
        - on_failed
      type: string
      description: 'This is the link type, allowing different endpoints to be targeted depending on the end state of the transaction. The link relation describes how this link relates to the previous call.'
      x-internal: true
    request:
      title: request
      type: object
      properties:
        merchantRefNum:
          type: string
          description: This is the merchant reference number created by the merchant and submitted as part of the request.
          maxLength: 255
          example: P1234
        accountTypes:
          type: array
          items:
            type: string
          description: 'This is the list of bank account types that will be presented. Possible values are: SAVING, CHEQUING'
        currencyCodes:
          type: array
          items:
            type: string
          description: 'This is the currency of the bank accounts that will be presented. Possible values are: CAD, USD'
        returnLinks:
          allOf:
            - $ref: '#/components/schemas/returnLinks'
            - description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status. The 'default' value is mandatory.
        bankScheme:
          allOf:
            - $ref: '#/components/schemas/bankScheme'
            - description: This is the bank scheme for which the merchant wants to validate the account.
              example: ACH
        id:
          type: string
          description: 'This is the ID returned in the response. This ID can be used for future associated requests, e,g., to look up the bank account verification details.'
          readOnly: true
          maxLength: 36
          example: 25f6dadf-176a-415f-95c9-6ff39ff697ba
        sessionId:
          type: string
          description: 'This is the encoded ID that will be used in the [API request to redirect the customer to the bank account validation page](#redirectionrequest). This ID is valid for 10 minutes.'
          readOnly: true
          maxLength: 255
          example: MjM5NWRlMTQtNDE4Yy0xMWU5LWIyMTAtZDY2M2JkODczZDkz
        status:
          allOf:
            - $ref: '#/components/schemas/status'
            - description: This shows the status of the bank account verification request.
              readOnly: true
              example: INITIATED
        statusMessage:
          type: string
          description: This message will be returned if the *status* is FAILED or INCOMPLETE.
          readOnly: true
          maxLength: 255
          example: message
        profile:
          allOf:
            - $ref: '#/components/schemas/profile'
            - description: This is some profile information about the customer.
        links:
          type: array
          items:
            $ref: '#/components/schemas/links'
          description: |-
            This is an array of links related to the resource.

            Typically you will have reference to any parent resources, and a reference to the child resource (if applicable).
            You may also see links for any call to action flows.
          readOnly: true
      x-internal: true
    returnLinkUrl:
      title: returnLinkUrl
      type: object
      properties:
        rel:
          allOf:
            - $ref: '#/components/schemas/rel'
            - description: 'This is the link type, allowing different endpoints to be targeted depending on the end state of the transaction. The link relation describes how this link relates to the previous call.'
        href:
          type: string
          description: The actual URL to which the customer will be redirected.
          example: 'https://mysite.com/return'
      description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status.
      readOnly: true
      x-internal: true
      x-examples:
        Example 1:
          rel: default
          href: 'https://mysite.com/return'
      x-stoplight:
        id: d05692847ec0a
    returnLinks:
      title: returnLinks
      type: object
      x-internal: false
      x-stoplight:
        id: 889af722fc791
      properties:
        returnLinks:
          type: array
          description: |-
            This is an array of links related to the resource.

            Typically you will have reference to any parent resources, and a reference to the child resource (if applicable).
            You may also see links for any call to action flows.
          readOnly: true
          items:
            $ref: '#/components/schemas/returnLinkUrl'
      x-examples:
        Example 1:
          returnLinks:
            - rel: default
              href: 'https://mysite.com/return'
      description: This is the URL to which to redirect the customer. You can customize the return URL based on the transaction status.
    verifications:
      title: verifications
      required:
        - merchantRefNum
        - profile
        - accountTypes
        - currencyCodes
        - returnLinks
        - bankScheme
      type: object
      properties:
        merchantRefNum:
          type: string
          description: This is the merchant reference number created by the merchant and submitted as part of the request.
          maxLength: 255
          example: '1323563'
        profile:
          $ref: '#/components/schemas/profile'
        accountTypes:
          type: array
          items:
            enum:
              - SAVING
              - CHEQUING
            type: string
          description: This is the type of the bank account.
        currencyCodes:
          type: array
          items:
            enum:
              - CAD
              - USD
            type: string
          description: This is the currency of the bank accounts that will be presented.
        returnLinks:
          type: array
          items:
            $ref: '#/components/schemas/returnLinkUrl'
          description: ''
        bankScheme:
          type: string
          items:
            enum:
              - ACH
              - EFT
          description: This is the bank scheme for which the merchant wants to validate the account.
          example: ACH
      example:
        merchantRefNum: '1323563'
        profile:
          firstName: Praveen
          middleName: Kumar
          lastName: Jain
          locale: en_CA
        accountTypes:
          - SAVING
          - CHEQUING
        currencyCodes:
          - CAD
          - USD
        returnLinks:
          - rel: default
            href: 'https://mysite.com/return'
        bankScheme: ACH
      x-internal: false
      x-stoplight:
        id: bc909db6dd9c5
    defaultReturnLinks:
      title: defaultReturnLinks
      required:
        - rel
        - href
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
      example:
        rel: default
        href: 'https://mysite.com/return'
      x-stoplight:
        id: 61c3edf53fad0
      x-internal: true
    status:
      title: status
      enum:
        - SUCCESS
        - FAILED
        - INITIATED
        - INCOMPLETE
      type: string
      description: This shows the status of the bank account verification request.
      readOnly: true
      example: INITIATED
      x-internal: true
    verifyThattheServiceIsAccessibleresponse:
      title: verifyThattheServiceIsAccessibleresponse
      required:
        - status
      type: object
      properties:
        status:
          type: string
      example:
        status: READY
      x-internal: true
      x-stoplight:
        id: 1080ea5dc733e
    bankSchemeAchEft:
      oneOf:
        - $ref: '#/components/schemas/ach'
        - $ref: '#/components/schemas/eft'
      x-internal: true
      x-stoplight:
        id: 6a9639046032d
      title: bankSchemeAchEft
  securitySchemes:
    httpBasic:
      type: http
      scheme: basic
security:
  - httpBasic: []
tags: []
